// Phase 5 — gRPC ingestion contract.
//
// 00-master-prd FR-1.2 and 01-architecture §4 require a second
// ingestion protocol that shares the HTTP path's downstream pipeline.
// This service is server-streaming with bidi: clients write Signal
// messages, server writes one Ack per accepted signal.
//
// Why bidi instead of unary "one RPC per signal":
//   * One TCP/HTTP2 connection amortised across thousands of signals;
//     no per-call handshake.
//   * Backpressure-aware: server reads at its own pace; if the
//     pipeline is full the server returns ACK with REJECTED_QUEUE_FULL
//     and the client knows to slow down.
//
// Why `bytes payload` instead of `google.protobuf.Struct`:
//   * Struct forces a JSON-shaped tree which costs ~µs per signal to
//     re-encode on both sides; we want to preserve the original JSON
//     bytes verbatim so it can stream straight into Mongo (Phase 3
//     stores it as native BSON via one Unmarshal).
//   * Clients usually have a serialised JSON blob already; sending it
//     as bytes avoids a parse-and-reserialise round-trip.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: ims/v1/signals.proto

package imsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SignalService_IngestSignals_FullMethodName = "/ims.v1.SignalService/IngestSignals"
)

// SignalServiceClient is the client API for SignalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SignalService is the only RPC surface in v1. Single bidi stream;
// extend with unary methods in later versions if needed.
type SignalServiceClient interface {
	// IngestSignals: client streams Signal, server streams Ack.
	//
	// The server commits to ACKing every Signal it reads, in order,
	// before the stream closes. Clients should buffer pending ACKs
	// up to ~100ms before considering a signal lost.
	IngestSignals(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Signal, Ack], error)
}

type signalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignalServiceClient(cc grpc.ClientConnInterface) SignalServiceClient {
	return &signalServiceClient{cc}
}

func (c *signalServiceClient) IngestSignals(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Signal, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SignalService_ServiceDesc.Streams[0], SignalService_IngestSignals_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Signal, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SignalService_IngestSignalsClient = grpc.BidiStreamingClient[Signal, Ack]

// SignalServiceServer is the server API for SignalService service.
// All implementations should embed UnimplementedSignalServiceServer
// for forward compatibility.
//
// SignalService is the only RPC surface in v1. Single bidi stream;
// extend with unary methods in later versions if needed.
type SignalServiceServer interface {
	// IngestSignals: client streams Signal, server streams Ack.
	//
	// The server commits to ACKing every Signal it reads, in order,
	// before the stream closes. Clients should buffer pending ACKs
	// up to ~100ms before considering a signal lost.
	IngestSignals(grpc.BidiStreamingServer[Signal, Ack]) error
}

// UnimplementedSignalServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignalServiceServer struct{}

func (UnimplementedSignalServiceServer) IngestSignals(grpc.BidiStreamingServer[Signal, Ack]) error {
	return status.Error(codes.Unimplemented, "method IngestSignals not implemented")
}
func (UnimplementedSignalServiceServer) testEmbeddedByValue() {}

// UnsafeSignalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignalServiceServer will
// result in compilation errors.
type UnsafeSignalServiceServer interface {
	mustEmbedUnimplementedSignalServiceServer()
}

func RegisterSignalServiceServer(s grpc.ServiceRegistrar, srv SignalServiceServer) {
	// If the following call panics, it indicates UnimplementedSignalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SignalService_ServiceDesc, srv)
}

func _SignalService_IngestSignals_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SignalServiceServer).IngestSignals(&grpc.GenericServerStream[Signal, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SignalService_IngestSignalsServer = grpc.BidiStreamingServer[Signal, Ack]

// SignalService_ServiceDesc is the grpc.ServiceDesc for SignalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ims.v1.SignalService",
	HandlerType: (*SignalServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IngestSignals",
			Handler:       _SignalService_IngestSignals_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ims/v1/signals.proto",
}
