// Phase 5 — gRPC ingestion contract.
//
// 00-master-prd FR-1.2 and 01-architecture §4 require a second
// ingestion protocol that shares the HTTP path's downstream pipeline.
// This service is server-streaming with bidi: clients write Signal
// messages, server writes one Ack per accepted signal.
//
// Why bidi instead of unary "one RPC per signal":
//   * One TCP/HTTP2 connection amortised across thousands of signals;
//     no per-call handshake.
//   * Backpressure-aware: server reads at its own pace; if the
//     pipeline is full the server returns ACK with REJECTED_QUEUE_FULL
//     and the client knows to slow down.
//
// Why `bytes payload` instead of `google.protobuf.Struct`:
//   * Struct forces a JSON-shaped tree which costs ~µs per signal to
//     re-encode on both sides; we want to preserve the original JSON
//     bytes verbatim so it can stream straight into Mongo (Phase 3
//     stores it as native BSON via one Unmarshal).
//   * Clients usually have a serialised JSON blob already; sending it
//     as bytes avoids a parse-and-reserialise round-trip.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ims/v1/signals.proto

package imsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum values prefixed with the enum name per buf STANDARD lint;
// proto3 convention requires the zero value first.
type Ack_AckStatus int32

const (
	Ack_ACK_STATUS_UNSPECIFIED         Ack_AckStatus = 0
	Ack_ACK_STATUS_ACCEPTED            Ack_AckStatus = 1
	Ack_ACK_STATUS_REJECTED_QUEUE_FULL Ack_AckStatus = 2
	Ack_ACK_STATUS_REJECTED_INVALID    Ack_AckStatus = 3
)

// Enum value maps for Ack_AckStatus.
var (
	Ack_AckStatus_name = map[int32]string{
		0: "ACK_STATUS_UNSPECIFIED",
		1: "ACK_STATUS_ACCEPTED",
		2: "ACK_STATUS_REJECTED_QUEUE_FULL",
		3: "ACK_STATUS_REJECTED_INVALID",
	}
	Ack_AckStatus_value = map[string]int32{
		"ACK_STATUS_UNSPECIFIED":         0,
		"ACK_STATUS_ACCEPTED":            1,
		"ACK_STATUS_REJECTED_QUEUE_FULL": 2,
		"ACK_STATUS_REJECTED_INVALID":    3,
	}
)

func (x Ack_AckStatus) Enum() *Ack_AckStatus {
	p := new(Ack_AckStatus)
	*p = x
	return p
}

func (x Ack_AckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Ack_AckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ims_v1_signals_proto_enumTypes[0].Descriptor()
}

func (Ack_AckStatus) Type() protoreflect.EnumType {
	return &file_ims_v1_signals_proto_enumTypes[0]
}

func (x Ack_AckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Ack_AckStatus.Descriptor instead.
func (Ack_AckStatus) EnumDescriptor() ([]byte, []int) {
	return file_ims_v1_signals_proto_rawDescGZIP(), []int{1, 0}
}

// Signal mirrors the HTTP JSON schema in 00-master-prd §4.2.
// Field numbers are stable; never renumber.
type Signal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Server mints a UUID if empty.
	SignalId string `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	// Required. e.g. "RDBMS_PRIMARY_01"
	ComponentId string `protobuf:"bytes,2,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	// Required. Enum string: API|MCP_HOST|CACHE|QUEUE|RDBMS|NOSQL|OTHER
	ComponentType string `protobuf:"bytes,3,opt,name=component_type,json=componentType,proto3" json:"component_type,omitempty"`
	// Required. Enum string: P0|P1|P2|P3
	Severity string `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	// Optional. Server stamps `now()` if zero.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Required. Which observability tool emitted this.
	Source string `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	// Free-form JSON bytes. Stored as native BSON in Mongo after one
	// Unmarshal in the processor.
	Payload       []byte `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_ims_v1_signals_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_ims_v1_signals_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_ims_v1_signals_proto_rawDescGZIP(), []int{0}
}

func (x *Signal) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

func (x *Signal) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *Signal) GetComponentType() string {
	if x != nil {
		return x.ComponentType
	}
	return ""
}

func (x *Signal) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Signal) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Signal) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Signal) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Ack is what the server returns per Signal. ACCEPTED is the happy
// path; the two REJECTED_* values are the backpressure / validation
// signals — mirror of HTTP's 503 and 400.
type Ack struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SignalId string                 `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	Status   Ack_AckStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=ims.v1.Ack_AckStatus" json:"status,omitempty"`
	// Human-readable error when status != ACCEPTED. Empty otherwise.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_ims_v1_signals_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_ims_v1_signals_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_ims_v1_signals_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

func (x *Ack) GetStatus() Ack_AckStatus {
	if x != nil {
		return x.Status
	}
	return Ack_ACK_STATUS_UNSPECIFIED
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_ims_v1_signals_proto protoreflect.FileDescriptor

const file_ims_v1_signals_proto_rawDesc = "" +
	"\n" +
	"\x14ims/v1/signals.proto\x12\x06ims.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf7\x01\n" +
	"\x06Signal\x12\x1b\n" +
	"\tsignal_id\x18\x01 \x01(\tR\bsignalId\x12!\n" +
	"\fcomponent_id\x18\x02 \x01(\tR\vcomponentId\x12%\n" +
	"\x0ecomponent_type\x18\x03 \x01(\tR\rcomponentType\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\"\xef\x01\n" +
	"\x03Ack\x12\x1b\n" +
	"\tsignal_id\x18\x01 \x01(\tR\bsignalId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.ims.v1.Ack.AckStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x85\x01\n" +
	"\tAckStatus\x12\x1a\n" +
	"\x16ACK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ACK_STATUS_ACCEPTED\x10\x01\x12\"\n" +
	"\x1eACK_STATUS_REJECTED_QUEUE_FULL\x10\x02\x12\x1f\n" +
	"\x1bACK_STATUS_REJECTED_INVALID\x10\x032A\n" +
	"\rSignalService\x120\n" +
	"\rIngestSignals\x12\x0e.ims.v1.Signal\x1a\v.ims.v1.Ack(\x010\x01B-Z+github.com/kubeboiii/ims/proto/ims/v1;imsv1b\x06proto3"

var (
	file_ims_v1_signals_proto_rawDescOnce sync.Once
	file_ims_v1_signals_proto_rawDescData []byte
)

func file_ims_v1_signals_proto_rawDescGZIP() []byte {
	file_ims_v1_signals_proto_rawDescOnce.Do(func() {
		file_ims_v1_signals_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ims_v1_signals_proto_rawDesc), len(file_ims_v1_signals_proto_rawDesc)))
	})
	return file_ims_v1_signals_proto_rawDescData
}

var file_ims_v1_signals_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ims_v1_signals_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ims_v1_signals_proto_goTypes = []any{
	(Ack_AckStatus)(0),            // 0: ims.v1.Ack.AckStatus
	(*Signal)(nil),                // 1: ims.v1.Signal
	(*Ack)(nil),                   // 2: ims.v1.Ack
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_ims_v1_signals_proto_depIdxs = []int32{
	3, // 0: ims.v1.Signal.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: ims.v1.Ack.status:type_name -> ims.v1.Ack.AckStatus
	1, // 2: ims.v1.SignalService.IngestSignals:input_type -> ims.v1.Signal
	2, // 3: ims.v1.SignalService.IngestSignals:output_type -> ims.v1.Ack
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ims_v1_signals_proto_init() }
func file_ims_v1_signals_proto_init() {
	if File_ims_v1_signals_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ims_v1_signals_proto_rawDesc), len(file_ims_v1_signals_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ims_v1_signals_proto_goTypes,
		DependencyIndexes: file_ims_v1_signals_proto_depIdxs,
		EnumInfos:         file_ims_v1_signals_proto_enumTypes,
		MessageInfos:      file_ims_v1_signals_proto_msgTypes,
	}.Build()
	File_ims_v1_signals_proto = out.File
	file_ims_v1_signals_proto_goTypes = nil
	file_ims_v1_signals_proto_depIdxs = nil
}
